apiVersion: v1
kind: Service
metadata:
  name: yes25-webapp-svc
  labels: { app: yes25-webapp }
spec:
  type: NodePort
  selector: { app: yes25-webapp }
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30081
